use std::{collections::HashSet, fs, path::Path};

use anyhow::{Context, Result, bail};

use crate::{
    input::PageEntry,
    model::{MokuroDocument, MokuroPage},
};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ForceScope {
    None,
    WholeVolume,
    Page(usize),
}

/// Load a compatible partial sidecar or prepare a fresh document.
///
/// # Errors
///
/// Returns an error when an existing sidecar is unreadable or incompatible
/// and the requested force scope does not authorize replacing it.
pub fn prepare_document(
    output_path: &Path,
    mut expected: MokuroDocument,
    entries: &[PageEntry],
    force_scope: ForceScope,
) -> Result<MokuroDocument> {
    if !output_path.exists() {
        return Ok(expected);
    }

    if force_scope == ForceScope::WholeVolume {
        return Ok(expected);
    }

    let bytes = fs::read(output_path)
        .with_context(|| format!("failed to read existing output {}", output_path.display()))?;
    let mut existing: MokuroDocument = match serde_json::from_slice(&bytes) {
        Ok(document) => document,
        Err(_) if force_scope != ForceScope::None => return Ok(expected),
        Err(error) => {
            return Err(error).with_context(|| {
                format!(
                    "existing output {} is not valid worker Mokuro JSON; use --force to replace it",
                    output_path.display()
                )
            });
        }
    };

    if let Err(error) = validate_compatible(&existing, &expected, entries) {
        if force_scope != ForceScope::None {
            return Ok(expected);
        }
        return Err(error).with_context(|| {
            format!(
                "existing output {} is not resumable; use --force to replace it",
                output_path.display()
            )
        });
    }

    if let ForceScope::Page(index) = force_scope {
        existing.pages[index] = None;
    }

    // Metadata generated by the current worker is authoritative while page
    // records from the compatible partial are retained.
    expected.mangaocr.failed_pages = normalized_failures(&existing, entries);
    expected.pages = existing.pages;
    Ok(expected)
}

/// Verify immutable cache metadata, page count, paths, and block line arrays.
///
/// # Errors
///
/// Returns an error describing the first incompatible cache property.
pub fn validate_compatible(
    existing: &MokuroDocument,
    expected: &MokuroDocument,
    entries: &[PageEntry],
) -> Result<()> {
    if existing.mangaocr.schema_version != expected.mangaocr.schema_version
        || existing.mangaocr.source != expected.mangaocr.source
        || existing.mangaocr.engine != expected.mangaocr.engine
        || existing.mangaocr.language != expected.mangaocr.language
    {
        bail!("source fingerprint, OCR engine, schema, or language changed");
    }
    if existing.pages.len() != entries.len() {
        bail!(
            "page count changed from {} to {}",
            existing.pages.len(),
            entries.len()
        );
    }

    for (index, (page, entry)) in existing.pages.iter().zip(entries).enumerate() {
        if let Some(page) = page {
            validate_page(page, entry, index)?;
        }
    }
    Ok(())
}

fn normalized_failures(
    document: &MokuroDocument,
    entries: &[PageEntry],
) -> Vec<crate::model::FailedPage> {
    let mut seen = HashSet::new();
    document
        .mangaocr
        .failed_pages
        .iter()
        .filter(|failure| {
            let Some(index) = failure.index.checked_sub(1) else {
                return false;
            };
            index < entries.len()
                && failure.img_path == entries[index].path
                && document.pages[index].is_none()
                && seen.insert(index)
        })
        .cloned()
        .collect()
}

fn validate_page(page: &MokuroPage, entry: &PageEntry, index: usize) -> Result<()> {
    if page.img_path != entry.path {
        bail!(
            "page {} path changed from {:?} to {:?}",
            index + 1,
            page.img_path,
            entry.path
        );
    }
    if page.img_width == 0 || page.img_height == 0 {
        bail!("page {} has invalid zero image dimensions", index + 1);
    }
    if page.lines_are_inconsistent() {
        bail!("page {} has inconsistent block line arrays", index + 1);
    }
    Ok(())
}

trait PageValidation {
    fn lines_are_inconsistent(&self) -> bool;
}

impl PageValidation for MokuroPage {
    fn lines_are_inconsistent(&self) -> bool {
        self.blocks
            .iter()
            .any(|block| block.lines.len() != block.lines_coords.len())
    }
}

#[cfg(test)]
mod tests {
    use tempfile::tempdir;

    use crate::{
        atomic::write_json_atomic,
        input::{InputManifest, PageEntry, ZIP_FINGERPRINT_ALGORITHM},
        model::{FailedPage, MOKURO_FORMAT_VERSION, MokuroBlock, MokuroDocument, MokuroPage},
    };

    use super::{ForceScope, prepare_document};

    fn entry(path: &str) -> PageEntry {
        PageEntry {
            path: path.to_owned(),
        }
    }

    fn expected(entries: &[PageEntry]) -> MokuroDocument {
        let manifest = InputManifest {
            source_size: 200,
            fingerprint_algorithm: ZIP_FINGERPRINT_ALGORITHM.to_owned(),
            fingerprint: "abc123".to_owned(),
            entries: entries.to_vec(),
        };
        MokuroDocument::empty(std::path::Path::new("/manga/volume.cbz"), &manifest, "ja")
    }

    fn page(path: &str) -> MokuroPage {
        MokuroPage {
            version: MOKURO_FORMAT_VERSION.to_owned(),
            img_path: path.to_owned(),
            img_width: 800,
            img_height: 1200,
            blocks: vec![MokuroBlock::new(
                [1, 2, 30, 40],
                true,
                20,
                vec![[[1, 2], [30, 2], [30, 40], [1, 40]]],
                vec!["日本語".to_owned()],
            )],
        }
    }

    #[test]
    fn compatible_partial_resumes_without_losing_page_indices() {
        let entries = vec![entry("1.jpg"), entry("2.jpg"), entry("10.jpg")];
        let mut partial = expected(&entries);
        partial.pages[1] = Some(page("2.jpg"));

        let directory = tempdir().expect("temporary directory");
        let output = directory.path().join("volume.mokuro");
        write_json_atomic(&output, &partial).expect("write partial");

        let resumed = prepare_document(&output, expected(&entries), &entries, ForceScope::None)
            .expect("resume compatible output");

        assert!(resumed.pages[0].is_none());
        assert_eq!(resumed.pages[1], partial.pages[1]);
        assert!(resumed.pages[2].is_none());
    }

    #[test]
    fn forcing_one_page_preserves_other_compatible_records() {
        let entries = vec![entry("1.jpg"), entry("2.jpg")];
        let mut partial = expected(&entries);
        partial.pages[0] = Some(page("1.jpg"));
        partial.pages[1] = Some(page("2.jpg"));

        let directory = tempdir().expect("temporary directory");
        let output = directory.path().join("volume.mokuro");
        write_json_atomic(&output, &partial).expect("write partial");

        let resumed = prepare_document(&output, expected(&entries), &entries, ForceScope::Page(1))
            .expect("prepare forced page");

        assert_eq!(resumed.pages[0], partial.pages[0]);
        assert!(resumed.pages[1].is_none());
    }

    #[test]
    fn mutable_failure_records_are_copied_without_affecting_compatibility() {
        let entries = vec![entry("1.jpg"), entry("2.jpg")];
        let mut partial = expected(&entries);
        partial.pages[0] = Some(page("1.jpg"));
        partial.mangaocr.failed_pages.push(FailedPage {
            index: 2,
            img_path: "2.jpg".to_owned(),
            error: "temporary outage".to_owned(),
            service_failure: true,
        });

        let directory = tempdir().expect("temporary directory");
        let output = directory.path().join("volume.mokuro");
        write_json_atomic(&output, &partial).expect("write partial");

        let resumed = prepare_document(&output, expected(&entries), &entries, ForceScope::None)
            .expect("resume failure metadata");
        assert_eq!(resumed.mangaocr.failed_pages, partial.mangaocr.failed_pages);
    }
}
